// Code generated by MockGen. DO NOT EDIT.
// Source: E:\workspace\kratos-demo\internal\bondProductApi\biz\interface.go

// Package mock_biz is a generated GoMock package.
package biz

import (
	context "context"
	sql "database/sql"
	reflect "reflect"

	domain "github.com/go-kratos/kratos-layout/internal/bondProductApi/biz/domain"
	dto "github.com/go-kratos/kratos-layout/internal/bondProductApi/biz/dto"
	gomock "github.com/golang/mock/gomock"
)

// MockRepoRegistry is a mock of RepoRegistry interface.
type MockRepoRegistry struct {
	ctrl     *gomock.Controller
	recorder *MockRepoRegistryMockRecorder
}

// MockRepoRegistryMockRecorder is the mock recorder for MockRepoRegistry.
type MockRepoRegistryMockRecorder struct {
	mock *MockRepoRegistry
}

// NewMockRepoRegistry creates a new mock instance.
func NewMockRepoRegistry(ctrl *gomock.Controller) *MockRepoRegistry {
	mock := &MockRepoRegistry{ctrl: ctrl}
	mock.recorder = &MockRepoRegistryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepoRegistry) EXPECT() *MockRepoRegistryMockRecorder {
	return m.recorder
}

// Product mocks base method.
func (m *MockRepoRegistry) Product() ProductRepo {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Product")
	ret0, _ := ret[0].(ProductRepo)
	return ret0
}

// Product indicates an expected call of Product.
func (mr *MockRepoRegistryMockRecorder) Product() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Product", reflect.TypeOf((*MockRepoRegistry)(nil).Product))
}

// MockProductRepo is a mock of ProductRepo interface.
type MockProductRepo struct {
	ctrl     *gomock.Controller
	recorder *MockProductRepoMockRecorder
}

// MockProductRepoMockRecorder is the mock recorder for MockProductRepo.
type MockProductRepoMockRecorder struct {
	mock *MockProductRepo
}

// NewMockProductRepo creates a new mock instance.
func NewMockProductRepo(ctrl *gomock.Controller) *MockProductRepo {
	mock := &MockProductRepo{ctrl: ctrl}
	mock.recorder = &MockProductRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProductRepo) EXPECT() *MockProductRepoMockRecorder {
	return m.recorder
}

// BannerList mocks base method.
func (m *MockProductRepo) BannerList(arg0 context.Context) ([]*domain.BondProductItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BannerList", arg0)
	ret0, _ := ret[0].([]*domain.BondProductItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BannerList indicates an expected call of BannerList.
func (mr *MockProductRepoMockRecorder) BannerList(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BannerList", reflect.TypeOf((*MockProductRepo)(nil).BannerList), arg0)
}

// ProductList mocks base method.
func (m *MockProductRepo) ProductList(arg0 context.Context, arg1 *dto.ProductQueryReq) ([]*domain.BondProductItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ProductList", arg0, arg1)
	ret0, _ := ret[0].([]*domain.BondProductItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ProductList indicates an expected call of ProductList.
func (mr *MockProductRepoMockRecorder) ProductList(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ProductList", reflect.TypeOf((*MockProductRepo)(nil).ProductList), arg0, arg1)
}

// MockTxManager is a mock of TxManager interface.
type MockTxManager struct {
	ctrl     *gomock.Controller
	recorder *MockTxManagerMockRecorder
}

// MockTxManagerMockRecorder is the mock recorder for MockTxManager.
type MockTxManagerMockRecorder struct {
	mock *MockTxManager
}

// NewMockTxManager creates a new mock instance.
func NewMockTxManager(ctrl *gomock.Controller) *MockTxManager {
	mock := &MockTxManager{ctrl: ctrl}
	mock.recorder = &MockTxManagerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTxManager) EXPECT() *MockTxManagerMockRecorder {
	return m.recorder
}

// BeginTx mocks base method.
func (m *MockTxManager) BeginTx(opts ...*sql.TxOptions) error {
	m.ctrl.T.Helper()
	varargs := []interface{}{}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "BeginTx", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// BeginTx indicates an expected call of BeginTx.
func (mr *MockTxManagerMockRecorder) BeginTx(opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BeginTx", reflect.TypeOf((*MockTxManager)(nil).BeginTx), opts...)
}

// CommitTx mocks base method.
func (m *MockTxManager) CommitTx() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CommitTx")
	ret0, _ := ret[0].(error)
	return ret0
}

// CommitTx indicates an expected call of CommitTx.
func (mr *MockTxManagerMockRecorder) CommitTx() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CommitTx", reflect.TypeOf((*MockTxManager)(nil).CommitTx))
}

// RollbackTx mocks base method.
func (m *MockTxManager) RollbackTx() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "RollbackTx")
}

// RollbackTx indicates an expected call of RollbackTx.
func (mr *MockTxManagerMockRecorder) RollbackTx() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RollbackTx", reflect.TypeOf((*MockTxManager)(nil).RollbackTx))
}

// SavePoint mocks base method.
func (m *MockTxManager) SavePoint(sp string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SavePoint", sp)
	ret0, _ := ret[0].(error)
	return ret0
}

// SavePoint indicates an expected call of SavePoint.
func (mr *MockTxManagerMockRecorder) SavePoint(sp interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SavePoint", reflect.TypeOf((*MockTxManager)(nil).SavePoint), sp)
}

// SetContext mocks base method.
func (m *MockTxManager) SetContext(ctx context.Context) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetContext", ctx)
}

// SetContext indicates an expected call of SetContext.
func (mr *MockTxManagerMockRecorder) SetContext(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetContext", reflect.TypeOf((*MockTxManager)(nil).SetContext), ctx)
}
