// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"kratos-demo/internal/config"
	"kratos-demo/internal/gateway"
	"kratos-demo/internal/gateway/registry"
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(server *config.Server, data *config.Data, logger log.Logger) (*kratos.App, func(), error) {
	registryClient, err := registry.NewNacosClientRegistry()
	if err != nil {
		return nil, nil, err
	}
	handler, err := gateway.NewHandler(registryClient)
	if err != nil {
		return nil, nil, err
	}
	httpServer := gateway.NewHTTPServer(server, logger, handler)
	app := newApp(logger, httpServer)
	return app, func() {
	}, nil
}
