// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"kratos-demo/internal/bondProductApi/biz"
	"kratos-demo/internal/bondProductApi/data"
	"kratos-demo/internal/bondProductApi/data/grom/repo"
	"kratos-demo/internal/bondProductApi/server"
	"kratos-demo/internal/bondProductApi/service"
	"kratos-demo/internal/config"
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(configServer *config.Server, configData *config.Data, logger log.Logger) (*kratos.App, func(), error) {
	orm := data.NewGormDB(configData)
	txManager := data.NewGormTxManager(orm)
	sess := data.NewGormSess(orm)
	productRepo := repo.NewGormProductRepo(sess, logger)
	repoRegistry := data.NewRepoRegistry(productRepo)
	productBiz := biz.NewProductBiz(txManager, repoRegistry, logger)
	productService := service.NewBondProductService(productBiz)
	v := server.NewRegisterSet(productService)
	grpcServer := server.NewGRPCServer(configServer, logger, v...)
	httpServer := server.NewHTTPServer(configServer, logger, v...)
	app := newApp(logger, grpcServer, httpServer)
	return app, func() {
	}, nil
}
